const BASE_URL = 'https://api.shev.movies.students.nomoredomains.icu';
const MOVIES_URL = 'https://localhost:3000';

const SUCCESSFUL_CODE = 200;
const INVALID_CODE = 400;


const movies = [
    {
      country: 'США',
      director: 'Райан Куглер',
      duration: 134,
      year: 2018,
      description: 'Теперь, когда Т’Чалла вернулся на престол в свою родную страну Ваканду, он должен использовать всю свою мощь для защиты своего народа от новой угрозы.',
      image: 'https://www.kinopoisk.ru/images/film_big/1047889.jpg',
      trailer: 'https://www.youtube.com/watch?v=QdpxoFcdORI',
      nameRU: 'Чёрная пантера',
      nameEN: 'Black Panther',
      thumbnail: 'https://www.kinopoisk.ru/images/film_big/1047889.jpg',
      movieId: 1,
      saved: true,
    },
    {
      country: 'США',
      director: 'Кристофер Нолан',
      duration: 106,
      year: 2010,
      description: 'Кобб — талантливый вор, лучший из лучших в опасном искусстве извлечения: он крадет ценные секреты из глубин подсознания во время сна, когда человеческий разум находится наиболее уязвимым.',
      image: 'https://www.kinopoisk.ru/images/film_big/447301.jpg',
      trailer: 'https://www.youtube.com/watch?v=8hP9D6kZseM',
      nameRU: 'Начало',
      nameEN: 'Inception',
      thumbnail: 'https://www.kinopoisk.ru/images/film_big/447301.jpg',
      movieId: 2,
      saved: true,
    },
    {
      country: 'США',
      director: 'Джон Фавро',
      duration: 126,
      year: 2008,
      description: 'История миллиардера-изобретателя Тони Старка, который создает высокотехнологичный костюм и становится героем, защищающим мир от зла.',
      image: 'https://www.kinopoisk.ru/images/film_big/61237.jpg',
      trailer: 'https://www.youtube.com/watch?v=8hYlB38asDY',
      nameRU: 'Железный человек',
      nameEN: 'Iron Man',
      thumbnail: 'https://www.kinopoisk.ru/images/film_big/61237.jpg',
      movieId: 3,
      saved: false,
    },
    {
      country: 'США',
      director: 'Кристофер Нолан',
      duration: 150,
      year: 2014,
      description: 'Группа исследователей использует новую технологию для погружения в человеческий разум и осуществления кражи информации из глубин психики.',
      image: 'https://www.kinopoisk.ru/images/film_big/258687.jpg',
      trailer: 'https://www.youtube.com/watch?v=8hP9D6kZseM',
      nameRU: 'Интерстеллар',
      nameEN: 'Interstellar',
      thumbnail: 'https://www.kinopoisk.ru/images/film_big/258687.jpg',
      movieId: 4,
      saved: false,
    },
    {
      country: 'США',
      director: 'Райан Куглер',
      duration: 134,
      year: 2018,
      description: 'Теперь, когда Т’Чалла вернулся на престол в свою родную страну Ваканду, он должен использовать всю свою мощь для защиты своего народа от новой угрозы.',
      image: 'https://www.kinopoisk.ru/images/film_big/1047889.jpg',
      trailer: 'https://www.youtube.com/watch?v=QdpxoFcdORI',
      nameRU: 'Чёрная пантера',
      nameEN: 'Black Panther',
      thumbnail: 'https://www.kinopoisk.ru/images/film_big/1047889.jpg',
      movieId: 5,
      saved: true,
    },
    {
      country: 'США',
      director: 'Кристофер Нолан',
      duration: 106,
      year: 2010,
      description: 'Кобб — талантливый вор, лучший из лучших в опасном искусстве извлечения: он крадет ценные секреты из глубин подсознания во время сна, когда человеческий разум находится наиболее уязвимым.',
      image: 'https://www.kinopoisk.ru/images/film_big/447301.jpg',
      trailer: 'https://www.youtube.com/watch?v=8hP9D6kZseM',
      nameRU: 'Начало',
      nameEN: 'Inception',
      thumbnail: 'https://www.kinopoisk.ru/images/film_big/447301.jpg',
      movieId: 6,
      saved: false,
    },
    {
      country: 'США',
      director: 'Джон Фавро',
      duration: 126,
      year: 2008,
      description: 'История миллиардера-изобретателя Тони Старка, который создает высокотехнологичный костюм и становится героем, защищающим мир от зла.',
      image: 'https://www.kinopoisk.ru/images/film_big/61237.jpg',
      trailer: 'https://www.youtube.com/watch?v=8hYlB38asDY',
      nameRU: 'Железный человек',
      nameEN: 'Iron Man',
      thumbnail: 'https://www.kinopoisk.ru/images/film_big/61237.jpg',
      movieId: 7,
      saved: true,
    },
    {
      country: 'США',
      director: 'Кристофер Нолан',
      duration: 150,
      year: 2014,
      description: 'Группа исследователей использует новую технологию для погружения в человеческий разум и осуществления кражи информации из глубин психики.',
      image: 'https://www.kinopoisk.ru/images/film_big/258687.jpg',
      trailer: 'https://www.youtube.com/watch?v=8hP9D6kZseM',
      nameRU: 'Интерстеллар',
      nameEN: 'Interstellar',
      thumbnail: 'https://www.kinopoisk.ru/images/film_big/258687.jpg',
      movieId: 8,
      saved: false,
    },
    {
      country: 'США',
      director: 'Райан Куглер',
      duration: 134,
      year: 2018,
      description: 'Теперь, когда Т’Чалла вернулся на престол в свою родную страну Ваканду, он должен использовать всю свою мощь для защиты своего народа от новой угрозы.',
      image: 'https://www.kinopoisk.ru/images/film_big/1047889.jpg',
      trailer: 'https://www.youtube.com/watch?v=QdpxoFcdORI',
      nameRU: 'Чёрная пантера',
      nameEN: 'Black Panther',
      thumbnail: 'https://www.kinopoisk.ru/images/film_big/1047889.jpg',
      movieId: 9,
      saved: true,
    },
    {
      country: 'США',
      director: 'Кристофер Нолан',
      duration: 106,
      year: 2010,
      description: 'Кобб — талантливый вор, лучший из лучших в опасном искусстве извлечения: он крадет ценные секреты из глубин подсознания во время сна, когда человеческий разум находится наиболее уязвимым.',
      image: 'https://www.kinopoisk.ru/images/film_big/447301.jpg',
      trailer: 'https://www.youtube.com/watch?v=8hP9D6kZseM',
      nameRU: 'Начало',
      nameEN: 'Inception',
      thumbnail: 'https://www.kinopoisk.ru/images/film_big/447301.jpg',
      movieId: 10,
      saved: true,
    },
    {
      country: 'США',
      director: 'Джон Фавро',
      duration: 126,
      year: 2008,
      description: 'История миллиардера-изобретателя Тони Старка, который создает высокотехнологичный костюм и становится героем, защищающим мир от зла.',
      image: 'https://www.kinopoisk.ru/images/film_big/61237.jpg',
      trailer: 'https://www.youtube.com/watch?v=8hYlB38asDY',
      nameRU: 'Железный человек',
      nameEN: 'Iron Man',
      thumbnail: 'https://www.kinopoisk.ru/images/film_big/61237.jpg',
      movieId: 11,
      saved: false,
    },
    {
      country: 'США',
      director: 'Кристофер Нолан',
      duration: 150,
      year: 2014,
      description: 'Группа исследователей использует новую технологию для погружения в человеческий разум и осуществления кражи информации из глубин психики.',
      image: 'https://www.kinopoisk.ru/images/film_big/258687.jpg',
      trailer: 'https://www.youtube.com/watch?v=8hP9D6kZseM',
      nameRU: 'Интерстеллар',
      nameEN: 'Interstellar',
      thumbnail: 'https://www.kinopoisk.ru/images/film_big/258687.jpg',
      movieId: 12,
      saved: false,
    },
    {
      country: 'США',
      director: 'Райан Куглер',
      duration: 134,
      year: 2018,
      description: 'Теперь, когда Т’Чалла вернулся на престол в свою родную страну Ваканду, он должен использовать всю свою мощь для защиты своего народа от новой угрозы.',
      image: 'https://www.kinopoisk.ru/images/film_big/1047889.jpg',
      trailer: 'https://www.youtube.com/watch?v=QdpxoFcdORI',
      nameRU: 'Чёрная пантера',
      nameEN: 'Black Panther',
      thumbnail: 'https://www.kinopoisk.ru/images/film_big/1047889.jpg',
      movieId: 13,
      saved: true,
    },
    {
      country: 'США',
      director: 'Кристофер Нолан',
      duration: 106,
      year: 2010,
      description: 'Кобб — талантливый вор, лучший из лучших в опасном искусстве извлечения: он крадет ценные секреты из глубин подсознания во время сна, когда человеческий разум находится наиболее уязвимым.',
      image: 'https://www.kinopoisk.ru/images/film_big/447301.jpg',
      trailer: 'https://www.youtube.com/watch?v=8hP9D6kZseM',
      nameRU: 'Начало',
      nameEN: 'Inception',
      thumbnail: 'https://www.kinopoisk.ru/images/film_big/447301.jpg',
      movieId: 14,
      saved: false,
    },
    {
      country: 'США',
      director: 'Джон Фавро',
      duration: 126,
      year: 2008,
      description: 'История миллиардера-изобретателя Тони Старка, который создает высокотехнологичный костюм и становится героем, защищающим мир от зла.',
      image: 'https://www.kinopoisk.ru/images/film_big/61237.jpg',
      trailer: 'https://www.youtube.com/watch?v=8hYlB38asDY',
      nameRU: 'Железный человек',
      nameEN: 'Iron Man',
      thumbnail: 'https://www.kinopoisk.ru/images/film_big/61237.jpg',
      movieId: 15,
      saved: true,
    },
    {
      country: 'США',
      director: 'Кристофер Нолан',
      duration: 150,
      year: 2014,
      description: 'Группа исследователей использует новую технологию для погружения в человеческий разум и осуществления кражи информации из глубин психики.',
      image: 'https://www.kinopoisk.ru/images/film_big/258687.jpg',
      trailer: 'https://www.youtube.com/watch?v=8hP9D6kZseM',
      nameRU: 'Интерстеллар',
      nameEN: 'Interstellar',
      thumbnail: 'https://www.kinopoisk.ru/images/film_big/258687.jpg',
      movieId: 16,
      saved: false,
    },
  ];

export {
  BASE_URL,
  MOVIES_URL,
  SUCCESSFUL_CODE,
  INVALID_CODE,
  movies
};
